version: "3.7"

services:
    base:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        image: base
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: base-service
        expose:
            - "3999"
        ports:
            - "3999:3999"
        command: npm run dev
