#-----[Root Fields]-----

type Query {
	getMessage(id: ID!): Message
	getMessages(id: ID!, pageSize: Int!, cursor: Int!): Messages!
	getChat(id: ID!): Chat
	getChats: [Chat!]!
	getUser: User
	getUsers(chat: ID!): [Member!]!
	#-----[Resources]-----
	getFile(id: ID!, type: FileType!): File
	getFiles(chat: ID!, type: FileType!, pageSize: Int!, cursor: Int!): Files!
	getLastFiles(chat: ID!, pageSize: Int!, type: FileType!): [File!]!
	getLinks(chat: ID!, pageSize: Int!, cursor: Int!): Links!
	getLastLinks(chat: ID!, pageSize: Int!): [String!]!
}

type Mutation {
	joinChat(chat: ID!): Boolean!
	createMessage(chat: ID!, message: MessageInput!): Message!
	deleteMessage(id: ID!): Boolean!
	editMessage(id: ID!, message: MessageInput!): Message!
	leaveChat(chat: ID!): Boolean!
	addUser(chat: ID!, username: String!, role: Role!): Boolean!
	removeUser(chat: ID!, username: String!): Boolean!
	createChat(name: String!): Chat!
	editChat(chat: ID!, name: String!): Chat!
	deleteChat(chat: ID!): Boolean!
	editUserRole(chat: ID!, username: String!, role: Role!): Member!
}

#-----[Inputs]-----
input MessageInput {
	message: String
	reply: ID
	#Files are included in the body of the request.
}

#-----[Interfaces]-----

interface Person {
	id: ID!
	username: String!
	avatar: ID!
}

#-----[Types]-----

type Message {
	id: ID!
	owner: ID!
	chat: ID!
	createdAt: DateTime!
	updatedAt: DateTime!
	message: String
	attachment: File
	reply: ID
}

type File {
	id: ID!
	name: String!
	mimeType: String!
	size: String!
}

type Links {
	hasMore: Boolean!
	cursor: Int!
	links: [String!]!
}

type Files {
	hasMore: Boolean!
	cursor: Int!
	files: [File!]!
}

type Messages {
	hasMore: Boolean!
	messages: [Message!]!
	cursor: Int!
}

type Chat {
	id: ID!
	name: String!
	notification: Boolean!
	users: [Member!]!
	latest: Message
}

type User implements Person {
	id: ID!
	username: String!
	avatar: ID!
}

type Member implements Person {
	id: ID!
	username: String!
	avatar: ID!
	role: Role!
}

#-----[Enum]-----
enum Role {
	admin
	owner
	member
}

enum FileType {
	file
	media
}

scalar DateTime
