version: "3.7"

services:
    direct-messaging:
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        image: direct-message
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: direct-messaging-service
        expose:
            - "4000"
        ports:
            - "4000:4000"
        command: npm run dev
